# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: drydock-api
spec:
  ports:
  - name: drydock-api
    port: {{ .Values.network.drydock.port }}
    {{ if .Values.network.drydock.node_port.enabled }}
    nodePort: {{ .Values.network.drydock.node_port.port }}
    {{ end }}
  selector:
    app: drydock
  {{ if .Values.network.drydock.node_port.enabled }}
  type: NodePort
  {{ end }}
